DELETE FROM "ChequeDetail" WHERE "feePaymentId" IN (SELECT fp.id FROM "FeePayment" fp JOIN "Organization" o ON fp."organizationId" = o.id WHERE o.slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "TeacherBankAccount" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "AcademicCalendar" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "MetaIntegration" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "ScheduledJob" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Certificate" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "StudentDocument" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "TransportEnrollment" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "FeePayment" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Fee" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "FeeCategory" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "StudentAttendance" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "ParentStudent" WHERE "studentId" IN (SELECT id FROM "Student" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "Student" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Parent" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "TeachingAssignment" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "IdCard" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "TeacherProfile" WHERE "teacherId" IN (SELECT id FROM "Teacher" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "Teacher" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "HallTicket" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "ExamEnrollment" WHERE "examId" IN (SELECT id FROM "Exam" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "ExamResult" WHERE "examId" IN (SELECT id FROM "Exam" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "Exam" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "ExamSession" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "ReportCard" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "AiAgentExecutionLog" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "AiAgentReport" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "AiAgentConfig" WHERE "agentId" IN (SELECT id FROM "AiAgent" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "AiAgent" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Section" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Subject" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Grade" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "GradingScale" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Vehicle" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Driver" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Helper" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "TransportStop" WHERE "routeId" IN (SELECT id FROM "TransportRoute" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "TransportRoute" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "LeaveStatusTimeline" WHERE "leaveId" IN (SELECT id FROM "Leave" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "Leave" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "NoticeAttachment" WHERE "noticeId" IN (SELECT id FROM "Notice" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "Notice" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "ComplaintStatusTimeline" WHERE "complaintId" IN (SELECT id FROM "AnonymousComplaint" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "AnonymousComplaint" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "LeadActivity" WHERE "leadId" IN (SELECT id FROM "Lead" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "Lead" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "NotificationLog" WHERE "notificationId" IN (SELECT id FROM "Notification" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "Notification" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "NotificationSetting" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Invitation" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Membership" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "SubscriptionPayment" WHERE "subscriptionId" IN (SELECT id FROM "Subscription" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "BillingEvent" WHERE "subscriptionId" IN (SELECT id FROM "Subscription" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "PricingSlab" WHERE "subscriptionId" IN (SELECT id FROM "Subscription" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%'));
DELETE FROM "Invoice" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Subscription" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "AcademicYear" WHERE "organizationId" IN (SELECT id FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%');
DELETE FROM "Organization" WHERE slug LIKE 'gurukul-vidyalaya-%';
DELETE FROM "Institution" WHERE slug LIKE 'gurukul-trust-%';
