'use server';

import { phonePayInitPayment } from './recordOnlinePayment';
import { getOrganizationRole, getOrganizationId } from '@/lib/auth';
import prisma from '@/lib/db';
import { Role } from '@/generated/prisma/enums';
import { revalidatePath } from 'next/cache';

/**
 * Generates a shareable payment link for a specific fee.
 * Only accessible by ADMIN and TEACHER roles.
 */
export const generateFeePaymentLink = async (feeId: string) => {
  // 1. Verify permissions
  const role = await getOrganizationRole();

  if (role !== Role.ADMIN && role !== Role.TEACHER) {
    throw new Error('Unauthorized: Only admins and teachers can generate payment links.');
  }

  // 2. Fetch the fee scoped to current organization (prevents cross-org access)
  const organizationId = await getOrganizationId();
  const fee = await prisma.fee.findFirst({
    where: { id: feeId, organizationId },
    select: {
      student: {
        select: {
          userId: true,
          firstName: true,
          lastName: true
        }
      }
    }
  });

  if (!fee) {
    throw new Error('Fee record not found.');
  }

  const studentUserId = fee.student.userId;
  if (!studentUserId) {
    throw new Error('Student has no associated user account to assign as payer.');
  }

  const studentName = `${fee.student.firstName} ${fee.student.lastName}`;
  const customNote = `Link generated by Admin for ${studentName}`;

  // 3. Initiate the payment with the student's userId and a custom note
  const result = await phonePayInitPayment(feeId, {
    payerId: studentUserId,
    note: customNote
  });

  if (result.success && result.redirectUrl) {
    revalidatePath('/dashboard/fees');
    return {
      success: true,
      paymentUrl: result.redirectUrl,
      transactionId: result.transactionId
    };
  }

  return {
    success: false,
    message: 'Failed to generate payment link.'
  };
};
