"use client"

import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import { AlertTriangle, MapPin, RefreshCw, Route as RouteIcon } from "lucide-react"
import { toast } from "sonner"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { generateRouteGeometry } from "@/lib/data/transport"

export type RoutePreviewStop = {
  id: string
  name: string
  order: number
  pickupTime: string | null
  latitude: number | null
  longitude: number | null
}

type RoutePreviewMapProps = {
  routeId: string
  routeName: string
  stops: RoutePreviewStop[]
  routeGeometry?: string | null
  distanceMeters?: number | null
  durationSeconds?: number | null
}

const PREVIEW_WIDTH = 640
const PREVIEW_HEIGHT = 280

function parseGeometry(value?: string | null): [number, number][] {
  if (!value) return []

  try {
    const parsed = JSON.parse(value) as unknown
    if (
      parsed &&
      typeof parsed === "object" &&
      "coordinates" in parsed &&
      Array.isArray((parsed as { coordinates?: unknown }).coordinates)
    ) {
      return (parsed as { coordinates: unknown[] }).coordinates.filter(isCoordinatePair)
    }
  } catch {
    return []
  }

  return []
}

function isCoordinatePair(value: unknown): value is [number, number] {
  return (
    Array.isArray(value) &&
    value.length === 2 &&
    typeof value[0] === "number" &&
    typeof value[1] === "number"
  )
}

function formatDistance(value?: number | null) {
  if (!value) return null
  if (value < 1000) return `${Math.round(value)} m`
  return `${(value / 1000).toFixed(1)} km`
}

function formatDuration(value?: number | null) {
  if (!value) return null
  return `${Math.max(1, Math.round(value / 60))} min`
}

export function RoutePreviewMap({
  routeId,
  routeName,
  stops,
  routeGeometry,
  distanceMeters,
  durationSeconds,
}: RoutePreviewMapProps) {
  const locatedStops = useMemo(
    () =>
      stops
        .filter(
          (stop): stop is RoutePreviewStop & { latitude: number; longitude: number } =>
            typeof stop.latitude === "number" && typeof stop.longitude === "number"
        )
        .sort((a, b) => a.order - b.order),
    [stops]
  )
  const fallbackCoordinates = useMemo<[number, number][]>(
    () => locatedStops.map((stop) => [stop.longitude, stop.latitude]),
    [locatedStops]
  )
  const waypointSignature = useMemo(
    () =>
      locatedStops
        .map((stop) => `${stop.order}:${stop.longitude.toFixed(6)},${stop.latitude.toFixed(6)}`)
        .join("|"),
    [locatedStops]
  )
  const savedGeometry = useMemo(() => parseGeometry(routeGeometry), [routeGeometry])
  const [roadCoordinates, setRoadCoordinates] = useState<[number, number][]>(savedGeometry)
  const [distance, setDistance] = useState<number | null>(distanceMeters ?? null)
  const [duration, setDuration] = useState<number | null>(durationSeconds ?? null)
  const [geometrySignature, setGeometrySignature] = useState(waypointSignature)
  const [isGenerating, setIsGenerating] = useState(false)
  const autoGeneratedRef = useRef(false)

  useEffect(() => {
    if (geometrySignature === waypointSignature) return

    setRoadCoordinates([])
    setDistance(null)
    setDuration(null)
  }, [geometrySignature, waypointSignature])

  const displayCoordinates = roadCoordinates.length >= 2 ? roadCoordinates : fallbackCoordinates
  const isRoadRoute = roadCoordinates.length >= 2
  const missingLocationCount = stops.length - locatedStops.length
  const distanceLabel = formatDistance(distance)
  const durationLabel = formatDuration(duration)
  const bounds = useMemo(() => {
    const coordinates = displayCoordinates.length > 0 ? displayCoordinates : fallbackCoordinates
    const lngs = coordinates.map(([lng]) => lng)
    const lats = coordinates.map(([, lat]) => lat)
    const minLng = Math.min(...lngs)
    const maxLng = Math.max(...lngs)
    const minLat = Math.min(...lats)
    const maxLat = Math.max(...lats)
    const lngPadding = Math.max((maxLng - minLng) * 0.18, 0.01)
    const latPadding = Math.max((maxLat - minLat) * 0.18, 0.01)

    return {
      minLng: minLng - lngPadding,
      maxLng: maxLng + lngPadding,
      minLat: minLat - latPadding,
      maxLat: maxLat + latPadding,
    }
  }, [displayCoordinates, fallbackCoordinates])
  const mapImageUrl = useMemo(() => {
    const bbox = [
      bounds.minLng.toFixed(6),
      bounds.minLat.toFixed(6),
      bounds.maxLng.toFixed(6),
      bounds.maxLat.toFixed(6),
    ].join(",")

    return `https://staticmap.openstreetmap.de/staticmap.php?bbox=${bbox}&size=${PREVIEW_WIDTH}x${PREVIEW_HEIGHT}&maptype=mapnik`
  }, [bounds])
  const projectPoint = useCallback(
    ([lng, lat]: [number, number]) => {
      const x = ((lng - bounds.minLng) / (bounds.maxLng - bounds.minLng)) * PREVIEW_WIDTH
      const y = ((bounds.maxLat - lat) / (bounds.maxLat - bounds.minLat)) * PREVIEW_HEIGHT

      return { x, y }
    },
    [bounds]
  )
  const pathData = useMemo(
    () =>
      displayCoordinates
        .map((coordinate, index) => {
          const { x, y } = projectPoint(coordinate)
          return `${index === 0 ? "M" : "L"} ${x.toFixed(1)} ${y.toFixed(1)}`
        })
        .join(" "),
    [displayCoordinates, projectPoint]
  )

  const generateRoadRoute = useCallback(async () => {
    if (locatedStops.length < 2) {
      toast.error("Add location for at least two stops before previewing route")
      return
    }

    setIsGenerating(true)
    try {
      const route = await generateRouteGeometry(routeId)
      const coordinates = parseGeometry(route.geometry)

      if (coordinates.length < 2) throw new Error("Route geometry missing")

      setRoadCoordinates(coordinates)
      setDistance(route.distanceMeters)
      setDuration(route.durationSeconds)
      setGeometrySignature(waypointSignature)
      toast.success("Road route preview saved")
    } catch {
      setRoadCoordinates([])
      toast.error("Road route unavailable. Showing simple stop-to-stop line.")
    } finally {
      setIsGenerating(false)
    }
  }, [locatedStops.length, routeId, waypointSignature])

  useEffect(() => {
    if (autoGeneratedRef.current || isRoadRoute || locatedStops.length < 2) return

    autoGeneratedRef.current = true
    void generateRoadRoute()
  }, [generateRoadRoute, isRoadRoute, locatedStops.length])

  return (
    <div className="mt-3 overflow-hidden rounded-lg border bg-background">
      <div className="flex flex-col gap-2 border-b p-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <div className="flex min-w-0 items-center gap-2">
            <RouteIcon className="h-4 w-4 shrink-0 text-primary" />
            <p className="truncate text-sm font-semibold">Route Preview</p>
          </div>
          <p className="mt-0.5 truncate text-xs text-muted-foreground">{routeName}</p>
        </div>
        <div className="flex shrink-0 flex-wrap items-center gap-2">
          <Badge variant={isRoadRoute ? "secondary" : "outline"} className="text-[11px]">
            {isRoadRoute ? "Road path" : "Simple line"}
          </Badge>
          {distanceLabel && <Badge variant="outline" className="text-[11px]">{distanceLabel}</Badge>}
          {durationLabel && <Badge variant="outline" className="text-[11px]">{durationLabel}</Badge>}
          <Button
            type="button"
            size="sm"
            variant="outline"
            className="h-8 gap-1.5"
            onClick={generateRoadRoute}
            disabled={isGenerating || locatedStops.length < 2}
          >
            <RefreshCw className={cn("h-3.5 w-3.5", isGenerating && "animate-spin")} />
            {isGenerating ? "Building" : "Refresh"}
          </Button>
        </div>
      </div>

      {locatedStops.length < 2 ? (
        <div className="flex min-h-36 flex-col items-center justify-center gap-2 p-4 text-center text-sm text-muted-foreground">
          <MapPin className="h-5 w-5" />
          Add location for at least two stops to preview this route.
        </div>
      ) : (
        <div
          className="relative h-72 overflow-hidden bg-muted bg-cover bg-center"
          style={{ backgroundImage: `url(${mapImageUrl})` }}
        >
          <svg
            viewBox={`0 0 ${PREVIEW_WIDTH} ${PREVIEW_HEIGHT}`}
            className="absolute inset-0 h-full w-full"
            role="img"
            aria-label={`${routeName} route preview`}
          >
            {displayCoordinates.length >= 2 && (
              <>
                <path
                  d={pathData}
                  fill="none"
                  stroke="#ffffff"
                  strokeWidth="6"
                  strokeOpacity="0.85"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
                <path
                  d={pathData}
                  fill="none"
                  stroke={isRoadRoute ? "#2563EB" : "#64748B"}
                  strokeWidth="3"
                  strokeDasharray={isRoadRoute ? undefined : "6 6"}
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </>
            )}

            {locatedStops.map((stop, index) => {
              const { x, y } = projectPoint([stop.longitude, stop.latitude])

              return (
                <g key={stop.id} transform={`translate(${x} ${y})`}>
                  <circle r="10" fill="#2563EB" stroke="#ffffff" strokeWidth="3" />
                  <text
                    y="4"
                    textAnchor="middle"
                    className="fill-white text-[10px] font-bold"
                  >
                    {index + 1}
                  </text>
                  <title>
                    {stop.name}{stop.pickupTime ? ` - Pickup: ${stop.pickupTime}` : ""}
                  </title>
                </g>
              )
            })}
          </svg>
          <div className="pointer-events-none absolute bottom-2 right-2 rounded bg-background/85 px-1.5 py-0.5 text-[10px] text-muted-foreground">
            OpenStreetMap
          </div>
        </div>
      )}

      {missingLocationCount > 0 && (
        <div className="flex items-start gap-2 border-t bg-amber-50 px-3 py-2 text-xs text-amber-800">
          <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
          {missingLocationCount} stop{missingLocationCount > 1 ? "s are" : " is"} missing location and won&apos;t appear on the map.
        </div>
      )}
    </div>
  )
}
