import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

function getVersion(): string {
  try {
    return execSync("git describe --tags --always", {
      cwd: root,
      encoding: "utf-8",
    }).trim();
  } catch {
    return "0.1.0";
  }
}

const version = getVersion();
const outPath = resolve(root, "lib", "version.ts");

writeFileSync(
  outPath,
  `// Auto-generated by scripts/generate-version.ts — do not edit
export const APP_VERSION = "${version}";
`,
);

console.log(`✓ lib/version.ts written (${version})`);
