import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
// Done. develop branch created locally and remote is in sync.
// Workflow:
// # 1. Start a feature
// git checkout develop
// git checkout -b feature/attendance-ai

// # 2. Test your changes on develop
// git checkout develop
// git merge feature/attendance-ai
// # test everything

// # 3. Ship to production
// git checkout main
// git merge develop
// npm version patch   # or minor
// git push origin main --tags
// main only gets merged when you're sure it's stable.
function getVersion(): string {
  try {
    return execSync("git describe --tags --always", {
      cwd: root,
      encoding: "utf-8",
    }).trim();
  } catch {
    return "0.1.0";
  }
}

const version = getVersion();
const outPath = resolve(root, "lib", "version.ts");

writeFileSync(
  outPath,
  `// Auto-generated by scripts/generate-version.ts — do not edit
export const APP_VERSION = "${version}";
`,
);

console.log(`✓ lib/version.ts written (${version})`);
