import * as React from 'react'
import prisma from '@/lib/db'
import { Resend } from 'resend'
import { google } from '@ai-sdk/google'
import { generateText } from 'ai'
import type { StudentAnalysis } from './execute-workflow'
import FeeSenseReportEmail from '@/emails/templates/FEE_SENSE_REPORT'

export type ReportMetrics = {
  totalStudents: number
  analyses: StudentAnalysis[]
  sent: number
  skipped: number
  errors: number
  voiceCallScheduled: number
  totalOverdue: number
}

function computeStats(analyses: StudentAnalysis[]) {
  const riskCounts = {
    LOW: analyses.filter(a => a.riskLevel === 'LOW').length,
    MEDIUM: analyses.filter(a => a.riskLevel === 'MEDIUM').length,
    HIGH: analyses.filter(a => a.riskLevel === 'HIGH').length,
    CRITICAL: analyses.filter(a => a.riskLevel === 'CRITICAL').length,
  }

  const topRisk = [...analyses]
    .sort((a, b) => b.riskScore - a.riskScore)
    .slice(0, 10)
    .map(a => ({
      studentId: a.studentId,
      studentName: a.studentName,
      riskScore: a.riskScore,
      riskLevel: a.riskLevel,
      pendingAmount: a.pendingAmount,
      issue: a.problems[0] || 'No specific issue',
    }))

  return { riskCounts, topRisk }
}

function buildReportText(metrics: ReportMetrics): string {
  const { riskCounts, topRisk } = computeStats(metrics.analyses)
  const reportDate = new Date().toLocaleDateString('en-IN', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  })

  const lines: string[] = [
    `FeeSense AI Daily Report — ${reportDate}`,
    '',
    `FeeSense AI completed its scheduled run for today. Here is a summary of what happened:`,
    '',
    `--- Overview ---`,
    `Total students processed: ${metrics.totalStudents}`,
    `Students with overdue fees: ${metrics.analyses.length}`,
    `Skipped (throttle / already notified): ${metrics.skipped}`,
    `${metrics.errors > 0 ? `Errors encountered: ${metrics.errors}` : 'Errors: 0 — all notifications sent successfully'}`,
    `Total overdue amount: ₹${metrics.totalOverdue.toLocaleString('en-IN')}`,
    '',
    `--- Risk Breakdown ---`,
    `Low: ${riskCounts.LOW}`,
    `Medium: ${riskCounts.MEDIUM}`,
    `High: ${riskCounts.HIGH}`,
    `Critical: ${riskCounts.CRITICAL}`,
    '',
    `--- Activity Summary ---`,
    `Reminder emails sent: ${metrics.sent}`,
    `Voice calls scheduled: ${metrics.voiceCallScheduled}`,
    '',
  ]

  if (metrics.analyses.length > 0) {
    const neverPaidCount = metrics.analyses.filter(a => a.paymentPattern === 'NEVER_PAID').length
    if (neverPaidCount > 0) {
      lines.push(`--- Key Observations ---`, `${neverPaidCount} students have never made a payment — personal follow-up recommended.`)
      lines.push('')
    }
  }

  if (topRisk.length > 0) {
    lines.push('--- Top Risk Students Needing Attention ---')
    for (const s of topRisk) {
      lines.push(`  ${s.studentName} — ${s.riskLevel} (₹${s.pendingAmount.toLocaleString('en-IN')}) — ${s.issue}`)
    }
    lines.push('')
  }

  if (metrics.errors > 0) {
    lines.push('--- Errors ---')
    lines.push(`${metrics.errors} notification(s) failed. Check the dashboard for details.`)
    lines.push('')
  }

  lines.push('--- What Happened ---')
  lines.push('FeeSense AI ran automatically in the background. No manual action was required to trigger this run. All eligible parents were notified via their preferred channel (WhatsApp, SMS, or Email). Voice calls were scheduled for critical cases.')
  lines.push('')
  lines.push('This report was generated by FeeSense AI — your automated fee collection assistant.')
  lines.push('--- End of Report ---')

  return lines.join('\n')
}

async function generateNLReport(metrics: ReportMetrics, model: string): Promise<string> {
  const stats = computeStats(metrics.analyses)
  try {
    const { text } = await generateText({
      model: google(model.replace('google/', '')),
      system: 'You are FeeSense AI — a helpful automated fee collection assistant for an Indian school. Write in a warm, professional tone as if you are a clerk reporting to the school principal or admin.',
      prompt: [
        `Generate a brief daily fee collection report summary. Here are the facts:`,
        `Date: ${new Date().toLocaleDateString('en-IN')}`,
        `Total students processed: ${metrics.totalStudents}`,
        `Students analysed (had overdue): ${metrics.analyses.length}`,
        `Skipped (throttle/cooldown): ${metrics.skipped}`,
        `Notification errors: ${metrics.errors}`,
        `Reminders sent: ${metrics.sent}`,
        `Voice calls scheduled: ${metrics.voiceCallScheduled}`,
        `Total overdue amount: ₹${metrics.totalOverdue}`,
        `Risk breakdown — Low: ${stats.riskCounts.LOW}, Medium: ${stats.riskCounts.MEDIUM}, High: ${stats.riskCounts.HIGH}, Critical: ${stats.riskCounts.CRITICAL}`,
        `Top risk students: ${stats.topRisk.map(s => `${s.studentName} (${s.riskLevel})`).join(', ')}`,
        '',
        'Write 2-3 sentences. Start with "Good morning" or "Good evening" based on time of day. Mention key highlights, any critical cases, and end with a reassuring note.',
      ].join('\n'),
    })
    return text
  } catch {
    const hour = Number(new Date().toLocaleString('en-IN', { hour: 'numeric', hour12: false, timeZone: 'Asia/Kolkata' }))
    const greeting = hour < 12 ? 'Good morning' : 'Good evening'
    const fallback = metrics.analyses.length === 0
      ? `Good day! No fees were overdue today. No notifications were needed.`
      : `${greeting}. FeeSense AI processed ${metrics.totalStudents} students today. ${metrics.sent} reminders were sent and ${metrics.voiceCallScheduled} voice calls were scheduled. ₹${metrics.totalOverdue.toLocaleString('en-IN')} remains outstanding. Everything is under control.`
    return fallback
  }
}

export type ReportRecipient = {
  id: string; email: string | null; name: string | null
}

/** Resolve report recipients — use configured deliverTo, or fallback to all org admins. */
async function resolveRecipients(
  organizationId: string,
  deliverToUserIds: string[],
): Promise<ReportRecipient[]> {
  if (deliverToUserIds.length > 0) {
    return prisma.user.findMany({
      where: { id: { in: deliverToUserIds } },
      select: { id: true, email: true, name: true },
    })
  }

  const memberships = await prisma.membership.findMany({
    where: { organizationId, role: 'ADMIN', status: 'ACTIVE' },
    select: {
      user: { select: { id: true, email: true, name: true } },
    },
  })

  return memberships.map(m => m.user).filter(u => u.email)
}

export async function generateAndStoreReport(
  agentId: string,
  organizationId: string,
  metrics: ReportMetrics,
  model: string,
  agentConfig: Record<string, unknown>,
): Promise<{ success: boolean; reportId?: string; error?: string }> {
  console.log('[generateReport] === Generating daily report ===', {
    totalStudents: metrics.totalStudents,
    analysesCount: metrics.analyses.length,
    sent: metrics.sent,
    skipped: metrics.skipped,
    errors: metrics.errors,
    totalOverdue: metrics.totalOverdue,
  })

  const { riskCounts, topRisk } = computeStats(metrics.analyses)
  const reportText = buildReportText(metrics)
  const nlReport = await generateNLReport(metrics, model)
  const neverPaidCount = metrics.analyses.filter(a => a.paymentPattern === 'NEVER_PAID').length

  // Log
  console.log('[generateReport] === REPORT ===')
  console.log(nlReport)
  console.log('[generateReport] === END ===')

  // Resolve recipients
  const reportConfig = (agentConfig?.report as { deliverTo?: string[]; channels?: string[] }) ?? {}
  const deliverToUserIds: string[] = Array.isArray(reportConfig.deliverTo) ? reportConfig.deliverTo : []
  const recipients = await resolveRecipients(organizationId, deliverToUserIds)

  if (recipients.length === 0) {
    console.warn('[generateReport] No recipients found — report stored but NOT delivered')
  } else {
    const deliverToEmails = recipients.map(r => r.email).filter((e): e is string => !!e)
    // Get org name for email template
    const org = await prisma.organization.findUnique({
      where: { id: organizationId },
      select: { name: true },
    })
    const orgName = org?.name ?? 'Your School'

    const reportDate = new Date().toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short', year: 'numeric' })

    // Send email with proper template
    const resend = new Resend(process.env.RESEND_API_KEY || '')
    for (const email of deliverToEmails) {
      try {
        const { error } = await resend.emails.send({
          from: process.env.RESEND_FROM_EMAIL ?? 'Shiksha Cloud <onboarding@resend.dev>',
          to: email,
          subject: `FeeSense AI Report — ${reportDate}`,
          react: React.createElement(FeeSenseReportEmail, {
            organizationName: orgName,
            date: reportDate,
            totalStudents: metrics.totalStudents,
            analysed: metrics.analyses.length,
            sent: metrics.sent,
            skipped: metrics.skipped,
            errors: metrics.errors,
            totalOverdue: metrics.totalOverdue,
            voiceCalls: metrics.voiceCallScheduled,
            riskCounts,
            topRisk,
            neverPaidCount,
            nlSummary: nlReport,
          }),
        })
        if (error) {
          console.error(`[generateReport] Resend error for ${email}:`, error)
        } else {
          console.log(`[generateReport] Report emailed to ${email}`)
        }
      } catch (emailErr) {
        console.error(`[generateReport] Failed to email report to ${email}:`, emailErr)
      }
    }

    // In-app notifications
    for (const user of recipients) {
      await prisma.notification.create({
        data: {
          organizationId,
          userId: user.id,
          type: 'FEE',
          title: `FeeSense AI Report — ${reportDate}`,
          message: `${nlReport}`,
          idempotencyKey: `feesense-report-${agentId}-${user.id}-${new Date().toISOString().split('T')[0]}`,
        },
      })
    }

    console.log(`[generateReport] Delivered to ${recipients.length} recipient(s): ${recipients.map(r => r.name || r.email || r.id).join(', ')}`)
  }

  // Store report
  const report = await prisma.aiAgentReport.create({
    data: {
      agentId,
      reportDate: new Date(),
      reportType: 'DAILY_SUMMARY',
      totalProcessed: metrics.totalStudents,
      highRiskCount: riskCounts.HIGH,
      mediumRiskCount: riskCounts.MEDIUM,
      lowRiskCount: riskCounts.LOW,
      emailsSent: metrics.sent,
      smsSent: 0,
      whatsappSent: 0,
      voiceCalls: metrics.voiceCallScheduled,
      data: {
        text: reportText,
        nlReport,
        topRiskItems: topRisk,
        totalOverdue: metrics.totalOverdue,
        metrics: {
          totalProcessed: metrics.totalStudents,
          skippedDueToCooldown: metrics.skipped,
          errors: metrics.errors,
          sent: metrics.sent,
          voiceCallScheduled: metrics.voiceCallScheduled,
        },
      },
      deliveredTo: recipients.map(r => r.email).filter((e): e is string => !!e),
    },
  })

  console.log('[generateReport] Done', {
    reportId: report.id,
    deliveredTo: recipients.length > 0 ? recipients.map(r => r.email || r.name || r.id) : 'NONE',
  })

  return { success: true, reportId: report.id }
}
